using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace SteamClone.DAL.Migrations
{
    /// <inheritdoc />
    public partial class Addedcountries : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "country",
                table: "users");

            migrationBuilder.AddColumn<int>(
                name: "country_id",
                table: "users",
                type: "integer",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.CreateTable(
                name: "countries",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    name = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    alpha2code = table.Column<string>(type: "character varying(10)", unicode: false, maxLength: 10, nullable: false),
                    alpha3code = table.Column<string>(type: "character varying(10)", unicode: false, maxLength: 10, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_countries", x => x.id);
                });

            migrationBuilder.InsertData(
                table: "countries",
                columns: new[] { "id", "alpha2code", "alpha3code", "name" },
                values: new object[,]
                {
                    { 1, "AF", "AFG", "Afghanistan" },
                    { 2, "AL", "ALB", "Albania" },
                    { 3, "DZ", "DZA", "Algeria" },
                    { 4, "AS", "ASM", "American Samoa" },
                    { 5, "AD", "AND", "Andorra" },
                    { 6, "AO", "AGO", "Angola" },
                    { 7, "AI", "AIA", "Anguilla" },
                    { 8, "AQ", "ATA", "Antarctica" },
                    { 9, "AG", "ATG", "Antigua and Barbuda" },
                    { 10, "AR", "ARG", "Argentina" },
                    { 11, "AM", "ARM", "Armenia" },
                    { 12, "AW", "ABW", "Aruba" },
                    { 13, "AU", "AUS", "Australia" },
                    { 14, "AT", "AUT", "Austria" },
                    { 15, "AZ", "AZE", "Azerbaijan" },
                    { 16, "BS", "BHS", "Bahamas" },
                    { 17, "BH", "BHR", "Bahrain" },
                    { 18, "BD", "BGD", "Bangladesh" },
                    { 19, "BB", "BRB", "Barbados" },
                    { 20, "BY", "BLR", "Belarus" },
                    { 21, "BE", "BEL", "Belgium" },
                    { 22, "BZ", "BLZ", "Belize" },
                    { 23, "BJ", "BEN", "Benin" },
                    { 24, "BM", "BMU", "Bermuda" },
                    { 25, "BT", "BTN", "Bhutan" },
                    { 26, "BO", "BOL", "Bolivia" },
                    { 27, "BQ", "BES", "Bonaire, Sint Eustatius and Saba" },
                    { 28, "BA", "BIH", "Bosnia and Herzegovina" },
                    { 29, "BW", "BWA", "Botswana" },
                    { 30, "BV", "BVT", "Bouvet Island" },
                    { 31, "BR", "BRA", "Brazil" },
                    { 32, "IO", "IOT", "British Indian Ocean Territory" },
                    { 33, "BN", "BRN", "Brunei Darussalam" },
                    { 34, "BG", "BGR", "Bulgaria" },
                    { 35, "BF", "BFA", "Burkina Faso" },
                    { 36, "BI", "BDI", "Burundi" },
                    { 37, "KH", "KHM", "Cambodia" },
                    { 38, "CM", "CMR", "Cameroon" },
                    { 39, "CA", "CAN", "Canada" },
                    { 40, "CV", "CPV", "Cape Verde" },
                    { 41, "KY", "CYM", "Cayman Islands" },
                    { 42, "CF", "CAF", "Central African Republic" },
                    { 43, "TD", "TCD", "Chad" },
                    { 44, "CL", "CHL", "Chile" },
                    { 45, "CN", "CHN", "China" },
                    { 46, "CX", "CXR", "Christmas Island" },
                    { 47, "CC", "CCK", "Cocos (Keeling) Islands" },
                    { 48, "CO", "COL", "Colombia" },
                    { 49, "KM", "COM", "Comoros" },
                    { 50, "CD", "COD", "Congo" },
                    { 51, "CG", "COG", "Congo" },
                    { 52, "CK", "COK", "Cook Islands" },
                    { 53, "CR", "CRI", "Costa Rica" },
                    { 54, "HR", "HRV", "Croatia" },
                    { 55, "CU", "CUB", "Cuba" },
                    { 56, "CW", "CUW", "Curaçao" },
                    { 57, "CY", "CYP", "Cyprus" },
                    { 58, "CZ", "CZE", "Czech Republic" },
                    { 59, "CI", "CIV", "Côte D'Ivoire" },
                    { 60, "DK", "DNK", "Denmark" },
                    { 61, "DJ", "DJI", "Djibouti" },
                    { 62, "DM", "DMA", "Dominica" },
                    { 63, "DO", "DOM", "Dominican Republic" },
                    { 64, "EC", "ECU", "Ecuador" },
                    { 65, "EG", "EGY", "Egypt" },
                    { 66, "SV", "SLV", "El Salvador" },
                    { 67, "GQ", "GNQ", "Equatorial Guinea" },
                    { 68, "ER", "ERI", "Eritrea" },
                    { 69, "EE", "EST", "Estonia" },
                    { 70, "ET", "ETH", "Ethiopia" },
                    { 71, "FK", "FLK", "Falkland Islands (Malvinas)" },
                    { 72, "FO", "FRO", "Faroe Islands" },
                    { 73, "FJ", "FJI", "Fiji" },
                    { 74, "FI", "FIN", "Finland" },
                    { 75, "FR", "FRA", "France" },
                    { 76, "GF", "GUF", "French Guiana" },
                    { 77, "PF", "PYF", "French Polynesia" },
                    { 78, "TF", "ATF", "French Southern Territories" },
                    { 79, "GA", "GAB", "Gabon" },
                    { 80, "GM", "GMB", "Gambia" },
                    { 81, "GE", "GEO", "Georgia" },
                    { 82, "DE", "DEU", "Germany" },
                    { 83, "GH", "GHA", "Ghana" },
                    { 84, "GI", "GIB", "Gibraltar" },
                    { 85, "GR", "GRC", "Greece" },
                    { 86, "GL", "GRL", "Greenland" },
                    { 87, "GD", "GRD", "Grenada" },
                    { 88, "GP", "GLP", "Guadeloupe" },
                    { 89, "GU", "GUM", "Guam" },
                    { 90, "GT", "GTM", "Guatemala" },
                    { 91, "GG", "GGY", "Guernsey" },
                    { 92, "GN", "GIN", "Guinea" },
                    { 93, "GW", "GNB", "Guinea-Bissau" },
                    { 94, "GY", "GUY", "Guyana" },
                    { 95, "HT", "HTI", "Haiti" },
                    { 96, "HM", "HMD", "Heard Island and Mcdonald Islands" },
                    { 97, "HN", "HND", "Honduras" },
                    { 98, "HK", "HKG", "Hong Kong" },
                    { 99, "HU", "HUN", "Hungary" },
                    { 100, "IS", "ISL", "Iceland" },
                    { 101, "IN", "IND", "India" },
                    { 102, "ID", "IDN", "Indonesia" },
                    { 103, "IR", "IRN", "Iran" },
                    { 104, "IQ", "IRQ", "Iraq" },
                    { 105, "IE", "IRL", "Ireland" },
                    { 106, "IM", "IMN", "Isle of Man" },
                    { 107, "IL", "ISR", "Israel" },
                    { 108, "IT", "ITA", "Italy" },
                    { 109, "JM", "JAM", "Jamaica" },
                    { 110, "JP", "JPN", "Japan" },
                    { 111, "JE", "JEY", "Jersey" },
                    { 112, "JO", "JOR", "Jordan" },
                    { 113, "KZ", "KAZ", "Kazakhstan" },
                    { 114, "KE", "KEN", "Kenya" },
                    { 115, "KI", "KIR", "Kiribati" },
                    { 116, "KW", "KWT", "Kuwait" },
                    { 117, "KG", "KGZ", "Kyrgyzstan" },
                    { 118, "LA", "LAO", "Lao People's Democratic Republic" },
                    { 119, "LV", "LVA", "Latvia" },
                    { 120, "LB", "LBN", "Lebanon" },
                    { 121, "LS", "LSO", "Lesotho" },
                    { 122, "LR", "LBR", "Liberia" },
                    { 123, "LY", "LBY", "Libya" },
                    { 124, "LI", "LIE", "Liechtenstein" },
                    { 125, "LT", "LTU", "Lithuania" },
                    { 126, "LU", "LUX", "Luxembourg" },
                    { 127, "MO", "MAC", "Macao" },
                    { 128, "MK", "MKD", "Macedonia" },
                    { 129, "MG", "MDG", "Madagascar" },
                    { 130, "MW", "MWI", "Malawi" },
                    { 131, "MY", "MYS", "Malaysia" },
                    { 132, "MV", "MDV", "Maldives" },
                    { 133, "ML", "MLI", "Mali" },
                    { 134, "MT", "MLT", "Malta" },
                    { 135, "MH", "MHL", "Marshall Islands" },
                    { 136, "MQ", "MTQ", "Martinique" },
                    { 137, "MR", "MRT", "Mauritania" },
                    { 138, "MU", "MUS", "Mauritius" },
                    { 139, "YT", "MYT", "Mayotte" },
                    { 140, "MX", "MEX", "Mexico" },
                    { 141, "FM", "FSM", "Micronesia" },
                    { 142, "MD", "MDA", "Moldova" },
                    { 143, "MC", "MCO", "Monaco" },
                    { 144, "MN", "MNG", "Mongolia" },
                    { 145, "ME", "MNE", "Montenegro" },
                    { 146, "MS", "MSR", "Montserrat" },
                    { 147, "MA", "MAR", "Morocco" },
                    { 148, "MZ", "MOZ", "Mozambique" },
                    { 149, "MM", "MMR", "Myanmar" },
                    { 150, "NA", "NAM", "Namibia" },
                    { 151, "NR", "NRU", "Nauru" },
                    { 152, "NP", "NPL", "Nepal" },
                    { 153, "NL", "NLD", "Netherlands" },
                    { 154, "NC", "NCL", "New Caledonia" },
                    { 155, "NZ", "NZL", "New Zealand" },
                    { 156, "NI", "NIC", "Nicaragua" },
                    { 157, "NE", "NER", "Niger" },
                    { 158, "NG", "NGA", "Nigeria" },
                    { 159, "NU", "NIU", "Niue" },
                    { 160, "NF", "NFK", "Norfolk Island" },
                    { 161, "KP", "PRK", "North Korea" },
                    { 162, "MP", "MNP", "Northern Mariana Islands" },
                    { 163, "NO", "NOR", "Norway" },
                    { 164, "OM", "OMN", "Oman" },
                    { 165, "PK", "PAK", "Pakistan" },
                    { 166, "PW", "PLW", "Palau" },
                    { 167, "PS", "PSE", "Palestinian Territory" },
                    { 168, "PA", "PAN", "Panama" },
                    { 169, "PG", "PNG", "Papua New Guinea" },
                    { 170, "PY", "PRY", "Paraguay" },
                    { 171, "PE", "PER", "Peru" },
                    { 172, "PH", "PHL", "Philippines" },
                    { 173, "PN", "PCN", "Pitcairn" },
                    { 174, "PL", "POL", "Poland" },
                    { 175, "PT", "PRT", "Portugal" },
                    { 176, "PR", "PRI", "Puerto Rico" },
                    { 177, "QA", "QAT", "Qatar" },
                    { 178, "RO", "ROU", "Romania" },
                    { 179, "RU", "RUS", "Russia" },
                    { 180, "RW", "RWA", "Rwanda" },
                    { 181, "RE", "REU", "Réunion" },
                    { 182, "BL", "BLM", "Saint Barthélemy" },
                    { 183, "SH", "SHN", "Saint Helena, Ascension and Tristan Da Cunha" },
                    { 184, "KN", "KNA", "Saint Kitts and Nevis" },
                    { 185, "LC", "LCA", "Saint Lucia" },
                    { 186, "MF", "MAF", "Saint Martin (French Part)" },
                    { 187, "PM", "SPM", "Saint Pierre and Miquelon" },
                    { 188, "VC", "VCT", "Saint Vincent and The Grenadines" },
                    { 189, "WS", "WSM", "Samoa" },
                    { 190, "SM", "SMR", "San Marino" },
                    { 191, "ST", "STP", "Sao Tome and Principe" },
                    { 192, "SA", "SAU", "Saudi Arabia" },
                    { 193, "SN", "SEN", "Senegal" },
                    { 194, "RS", "SRB", "Serbia" },
                    { 195, "SC", "SYC", "Seychelles" },
                    { 196, "SL", "SLE", "Sierra Leone" },
                    { 197, "SG", "SGP", "Singapore" },
                    { 198, "SX", "SXM", "Sint Maarten (Dutch Part)" },
                    { 199, "SK", "SVK", "Slovakia" },
                    { 200, "SI", "SVN", "Slovenia" },
                    { 201, "SB", "SLB", "Solomon Islands" },
                    { 202, "SO", "SOM", "Somalia" },
                    { 203, "ZA", "ZAF", "South Africa" },
                    { 204, "GS", "SGS", "South Georgia" },
                    { 205, "KR", "KOR", "South Korea" },
                    { 206, "SS", "SSD", "South Sudan" },
                    { 207, "ES", "ESP", "Spain" },
                    { 208, "LK", "LKA", "Sri Lanka" },
                    { 209, "SD", "SDN", "Sudan" },
                    { 210, "SR", "SUR", "Suriname" },
                    { 211, "SJ", "SJM", "Svalbard and Jan Mayen" },
                    { 212, "SZ", "SWZ", "Swaziland" },
                    { 213, "SE", "SWE", "Sweden" },
                    { 214, "CH", "CHE", "Switzerland" },
                    { 215, "SY", "SYR", "Syrian Arab Republic" },
                    { 216, "TW", "TWN", "Taiwan" },
                    { 217, "TJ", "TJK", "Tajikistan" },
                    { 218, "TZ", "TZA", "Tanzania" },
                    { 219, "TH", "THA", "Thailand" },
                    { 220, "TL", "TLS", "Timor-Leste" },
                    { 221, "TG", "TGO", "Togo" },
                    { 222, "TK", "TKL", "Tokelau" },
                    { 223, "TO", "TON", "Tonga" },
                    { 224, "TT", "TTO", "Trinidad and Tobago" },
                    { 225, "TN", "TUN", "Tunisia" },
                    { 226, "TR", "TUR", "Turkey" },
                    { 227, "TM", "TKM", "Turkmenistan" },
                    { 228, "TC", "TCA", "Turks and Caicos Islands" },
                    { 229, "TV", "TUV", "Tuvalu" },
                    { 230, "UG", "UGA", "Uganda" },
                    { 231, "UA", "UKR", "Ukraine" },
                    { 232, "AE", "ARE", "United Arab Emirates" },
                    { 233, "GB", "GBR", "United Kingdom" },
                    { 234, "US", "USA", "United States" },
                    { 235, "UM", "UMI", "United States Minor Outlying Islands" },
                    { 236, "UY", "URY", "Uruguay" },
                    { 237, "UZ", "UZB", "Uzbekistan" },
                    { 238, "VU", "VUT", "Vanuatu" },
                    { 239, "VA", "VAT", "Vatican City" },
                    { 240, "VE", "VEN", "Venezuela" },
                    { 241, "VN", "VNM", "Viet Nam" },
                    { 242, "VG", "VGB", "Virgin Islands, British" },
                    { 243, "VI", "VIR", "Virgin Islands, U.S." },
                    { 244, "WF", "WLF", "Wallis and Futuna" },
                    { 245, "EH", "ESH", "Western Sahara" },
                    { 246, "YE", "YEM", "Yemen" },
                    { 247, "ZM", "ZMB", "Zambia" },
                    { 248, "ZW", "ZWE", "Zimbabwe" },
                    { 249, "AX", "ALA", "Åland Islands" }
                });

            migrationBuilder.CreateIndex(
                name: "ix_users_country_id",
                table: "users",
                column: "country_id");

            migrationBuilder.AddForeignKey(
                name: "fk_users_countries_country_id",
                table: "users",
                column: "country_id",
                principalTable: "countries",
                principalColumn: "id",
                onDelete: ReferentialAction.Restrict);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "fk_users_countries_country_id",
                table: "users");

            migrationBuilder.DropTable(
                name: "countries");

            migrationBuilder.DropIndex(
                name: "ix_users_country_id",
                table: "users");

            migrationBuilder.DropColumn(
                name: "country_id",
                table: "users");

            migrationBuilder.AddColumn<string>(
                name: "country",
                table: "users",
                type: "character varying(50)",
                maxLength: 50,
                nullable: false,
                defaultValue: "");
        }
    }
}
