using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace SteamClone.DAL.Migrations
{
    /// <inheritdoc />
    public partial class AddedLanguages : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "languages",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    name = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    code = table.Column<string>(type: "character varying(10)", unicode: false, maxLength: 10, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_languages", x => x.id);
                });

            migrationBuilder.InsertData(
                table: "languages",
                columns: new[] { "id", "code", "name" },
                values: new object[,]
                {
                    { 1, "aa", "Afar" },
                    { 2, "ab", "Abkhazian" },
                    { 3, "ae", "Avestan" },
                    { 4, "af", "Afrikaans" },
                    { 5, "ak", "Akan" },
                    { 6, "am", "Amharic" },
                    { 7, "an", "Aragonese" },
                    { 8, "ar", "Arabic" },
                    { 9, "as", "Assamese" },
                    { 10, "av", "Avaric" },
                    { 11, "ay", "Aymara" },
                    { 12, "az", "Azerbaijani" },
                    { 13, "ba", "Bashkir" },
                    { 14, "be", "Belarusian" },
                    { 15, "bg", "Bulgarian" },
                    { 16, "bh", "Bihari languages" },
                    { 17, "bi", "Bislama" },
                    { 18, "bm", "Bambara" },
                    { 19, "bn", "Bengali" },
                    { 20, "bo", "Tibetan" },
                    { 21, "br", "Breton" },
                    { 22, "bs", "Bosnian" },
                    { 23, "ca", "Catalan; Valencian" },
                    { 24, "ce", "Chechen" },
                    { 25, "ch", "Chamorro" },
                    { 26, "co", "Corsican" },
                    { 27, "cr", "Cree" },
                    { 28, "cs", "Czech" },
                    { 29, "cv", "Chuvash" },
                    { 30, "cy", "Welsh" },
                    { 31, "da", "Danish" },
                    { 32, "de", "German" },
                    { 33, "dv", "Divehi; Dhivehi; Maldivian" },
                    { 34, "dz", "Dzongkha" },
                    { 35, "ee", "Ewe" },
                    { 36, "el", "Greek, Modern (1453-)" },
                    { 37, "en", "English" },
                    { 38, "eo", "Esperanto" },
                    { 39, "es", "Spanish; Castilian" },
                    { 40, "et", "Estonian" },
                    { 41, "eu", "Basque" },
                    { 42, "fa", "Persian" },
                    { 43, "ff", "Fulah" },
                    { 44, "fi", "Finnish" },
                    { 45, "fj", "Fijian" },
                    { 46, "fo", "Faroese" },
                    { 47, "fr", "French" },
                    { 48, "fy", "Western Frisian" },
                    { 49, "ga", "Irish" },
                    { 50, "gd", "Gaelic; Scomttish Gaelic" },
                    { 51, "gl", "Galician" },
                    { 52, "gn", "Guarani" },
                    { 53, "gu", "Gujarati" },
                    { 54, "gv", "Manx" },
                    { 55, "ha", "Hausa" },
                    { 56, "he", "Hebrew" },
                    { 57, "hi", "Hindi" },
                    { 58, "ho", "Hiri Motu" },
                    { 59, "hr", "Croatian" },
                    { 60, "ht", "Haitian; Haitian Creole" },
                    { 61, "hu", "Hungarian" },
                    { 62, "hy", "Armenian" },
                    { 63, "hz", "Herero" },
                    { 64, "id", "Indonesian" },
                    { 65, "ie", "Interlingue; Occidental" },
                    { 66, "ig", "Igbo" },
                    { 67, "ii", "Sichuan Yi; Nuosu" },
                    { 68, "ik", "Inupiaq" },
                    { 69, "io", "Ido" },
                    { 70, "is", "Icelandic" },
                    { 71, "it", "Italian" },
                    { 72, "iu", "Inuktitut" },
                    { 73, "ja", "Japanese" },
                    { 74, "jv", "Javanese" },
                    { 75, "ka", "Georgian" },
                    { 76, "kg", "Kongo" },
                    { 77, "ki", "Kikuyu; Gikuyu" },
                    { 78, "kj", "Kuanyama; Kwanyama" },
                    { 79, "kk", "Kazakh" },
                    { 80, "kl", "Kalaallisut; Greenlandic" },
                    { 81, "km", "Central Khmer" },
                    { 82, "kn", "Kannada" },
                    { 83, "ko", "Korean" },
                    { 84, "kr", "Kanuri" },
                    { 85, "ks", "Kashmiri" },
                    { 86, "ku", "Kurdish" },
                    { 87, "kv", "Komi" },
                    { 88, "kw", "Cornish" },
                    { 89, "ky", "Kirghiz; Kyrgyz" },
                    { 90, "la", "Latin" },
                    { 91, "lb", "Luxembourgish; Letzeburgesch" },
                    { 92, "lg", "Ganda" },
                    { 93, "li", "Limburgan; Limburger; Limburgish" },
                    { 94, "ln", "Lingala" },
                    { 95, "lo", "Lao" },
                    { 96, "lt", "Lithuanian" },
                    { 97, "lu", "Luba-Katanga" },
                    { 98, "lv", "Latvian" },
                    { 99, "mg", "Malagasy" },
                    { 100, "mh", "Marshallese" },
                    { 101, "mi", "Maori" },
                    { 102, "mk", "Macedonian" },
                    { 103, "ml", "Malayalam" },
                    { 104, "mn", "Mongolian" },
                    { 105, "mr", "Marathi" },
                    { 106, "ms", "Malay" },
                    { 107, "mt", "Maltese" },
                    { 108, "my", "Burmese" },
                    { 109, "na", "Nauru" },
                    { 110, "nb", "Bokmål, Norwegian; Norwegian Bokmål" },
                    { 111, "nd", "Ndebele, North; North Ndebele" },
                    { 112, "ne", "Nepali" },
                    { 113, "ng", "Ndonga" },
                    { 114, "nl", "Dutch; Flemish" },
                    { 115, "nn", "Norwegian Nynorsk; Nynorsk, Norwegian" },
                    { 116, "no", "Norwegian" },
                    { 117, "nr", "Ndebele, South; South Ndebele" },
                    { 118, "nv", "Navajo; Navaho" },
                    { 119, "ny", "Chichewa; Chewa; Nyanja" },
                    { 120, "oc", "Occitan (post 1500)" },
                    { 121, "oj", "Ojibwa" },
                    { 122, "om", "Oromo" },
                    { 123, "or", "Oriya" },
                    { 124, "os", "Ossetian; Ossetic" },
                    { 125, "pa", "Panjabi; Punjabi" },
                    { 126, "pi", "Pali" },
                    { 127, "pl", "Polish" },
                    { 128, "ps", "Pushto; Pashto" },
                    { 129, "pt", "Portuguese" },
                    { 130, "qu", "Quechua" },
                    { 131, "rm", "Romansh" },
                    { 132, "rn", "Rundi" },
                    { 133, "ro", "Romanian; Moldavian; Moldovan" },
                    { 134, "ru", "Russian" },
                    { 135, "rw", "Kinyarwanda" },
                    { 136, "sa", "Sanskrit" },
                    { 137, "sc", "Sardinian" },
                    { 138, "sd", "Sindhi" },
                    { 139, "se", "Northern Sami" },
                    { 140, "sg", "Sango" },
                    { 141, "si", "Sinhala; Sinhalese" },
                    { 142, "sk", "Slovak" },
                    { 143, "sl", "Slovenian" },
                    { 144, "sm", "Samoan" },
                    { 145, "sn", "Shona" },
                    { 146, "so", "Somali" },
                    { 147, "sq", "Albanian" },
                    { 148, "sr", "Serbian" },
                    { 149, "ss", "Swati" },
                    { 150, "st", "Sotho, Southern" },
                    { 151, "su", "Sundanese" },
                    { 152, "sv", "Swedish" },
                    { 153, "sw", "Swahili" },
                    { 154, "ta", "Tamil" },
                    { 155, "te", "Telugu" },
                    { 156, "tg", "Tajik" },
                    { 157, "th", "Thai" },
                    { 158, "ti", "Tigrinya" },
                    { 159, "tk", "Turkmen" },
                    { 160, "tl", "Tagalog" },
                    { 161, "tn", "Tswana" },
                    { 162, "to", "Tonga (Tonga Islands)" },
                    { 163, "tr", "Turkish" },
                    { 164, "ts", "Tsonga" },
                    { 165, "tt", "Tatar" },
                    { 166, "tw", "Twi" },
                    { 167, "ty", "Tahitian" },
                    { 168, "ug", "Uighur; Uyghur" },
                    { 169, "uk", "Ukrainian" },
                    { 170, "ur", "Urdu" },
                    { 171, "uz", "Uzbek" },
                    { 172, "ve", "Venda" },
                    { 173, "vi", "Vietnamese" },
                    { 174, "vo", "Volapük" },
                    { 175, "wa", "Walloon" },
                    { 176, "wo", "Wolof" },
                    { 177, "xh", "Xhosa" },
                    { 178, "yi", "Yiddish" },
                    { 179, "yo", "Yoruba" },
                    { 180, "za", "Zhuang; Chuang" },
                    { 181, "zh", "Chinese" },
                    { 182, "zu", "Zulu" }
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "languages");
        }
    }
}
